# Generated by Django 2.0.5 on 2021-02-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210209_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetail',
            old_name='Product',
            new_name='product',
        ),
    ]
