# Generated by Django 2.0.5 on 2021-02-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210209_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='status',
            field=models.CharField(blank=True, default='POR ENTREGAR', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
    ]
