# Generated by Django 2.0.5 on 2021-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210223_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('ZELLE', 'ZELLE'), ('TRANSFERENCIA BS', 'TRANSFERENCIA BS'), ('TRANSFERENCIA $', 'TRANSFERENCIA $'), ('PAGO MOVIL', 'PAGO MOVIL'), ('EFECTIVO', 'EFECTIVO')], default='TRANSFERENCIA BS', max_length=20),
        ),
    ]
