# Generated by Django 2.0.5 on 2021-04-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20210303_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.Bank'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SalePromotion', to='promotions.Promotion'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail_sale', to='sales.Sale'),
        ),
    ]
