# Generated by Django 2.0.5 on 2021-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210412_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
