# Generated by Django 2.0.5 on 2021-04-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SalePromotion', to='promotions.Promotion'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SaleProduct', to='products.Product'),
        ),
    ]
