# Generated by Django 2.0.5 on 2021-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='agent',
            field=models.CharField(default='s/a', max_length=255),
            preserve_default=False,
        ),
    ]
