# Generated by Django 2.0.5 on 2021-01-18 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('products', '0004_auto_20210118_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristics.Characteristic')),
            ],
            options={
                'verbose_name': 'Detalle de producto',
                'verbose_name_plural': 'Detalles de productos',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.FileField(upload_to='uploads')),
            ],
            options={
                'verbose_name': 'Galeria de producto',
                'verbose_name_plural': 'Galerias de productos',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
    ]
