# Generated by Django 2.0.5 on 2021-02-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210120_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature', to='characteristics.Characteristic'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_product', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picture', to='products.Product'),
        ),
    ]
