# Generated by Django 2.0.5 on 2021-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210208_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.FileField(null=True, upload_to='products'),
        ),
    ]
