# Generated by Django 2.0.5 on 2021-01-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='porvider',
            new_name='provider',
        ),
    ]
