# Generated by Django 2.0.5 on 2021-02-02 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210124_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseProduct', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseDetail', to='purchases.Purchase'),
        ),
    ]
