# Generated by Django 2.0.5 on 2021-04-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_category', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.FileField(null=True, upload_to='promotions'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotiondetail_product', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='promotion',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, related_name='promotion_detail', to='promotions.Promotion'),
        ),
    ]
