# Generated by Django 2.0.5 on 2021-02-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20210212_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_category', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotiondetail_product', to='products.Product'),
        ),
    ]
