# Generated by Django 2.0.5 on 2021-04-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20210414_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='image',
        ),
        migrations.AlterField(
            model_name='promotiondetail',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_detail', to='promotions.Promotion'),
        ),
    ]
