# Generated by Django 2.0.5 on 2021-04-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20210415_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiondetail',
            name='promotion',
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.FileField(null=True, upload_to='promotions'),
        ),
    ]
