# Generated by Django 2.0.5 on 2021-04-15 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20210415_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiondetail',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_detail', to='promotions.Promotion'),
        ),
    ]
