# Generated by Django 2.0.5 on 2021-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210204_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='method',
            name='payment_type',
            field=models.CharField(choices=[('ZELLE', 'ZELLE'), ('TRANSFERENCIA $', 'TRANSFERENCIA $'), ('TRANSFERENCIA BS', 'TRANSFERENCIA BS'), ('PAGO MOVIL', 'PAGO MOVIL'), ('EFECTIVO', 'EFECTIVO')], default='TRANSFERENCIA $', max_length=20),
        ),
    ]
