# Generated by Django 2.0.5 on 2021-01-18 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('coin', models.CharField(choices=[('USD', 'USD'), ('BS', 'BS')], default='USD', max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
            },
        ),
        migrations.CreateModel(
            name='ComboDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.IntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='combos.Combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
            options={
                'verbose_name': 'Detalle de combo',
                'verbose_name_plural': 'Detalles de Combos',
            },
        ),
    ]
