# Generated by Django 2.0.5 on 2021-01-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
