# Generated by Django 2.0.5 on 2021-01-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0002_auto_20210118_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
