# Generated by Django 2.0.5 on 2021-02-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0004_auto_20210118_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiondetail',
            name='combo',
        ),
        migrations.AddField(
            model_name='promotiondetail',
            name='promotion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_detail', to='combos.Promotion'),
        ),
    ]
