# Generated by Django 2.0.5 on 2021-02-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_auto_20210204_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoppingcart', to=settings.AUTH_USER_MODEL),
        ),
    ]
