# Generated by Django 2.0.5 on 2021-04-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20210226_1722'),
        ('shoppingcart', '0004_auto_20210305_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='promotions.Promotion'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product'),
        ),
    ]
